name = "lumina-neo-backend"
main = "src/index.ts"
compatibility_date = "2023-10-01"

routes = [
	{ pattern = "api.lumina-neo.peakits.com", custom_domain = true }
]

# KV Namespace Bindings
[[kv_namespaces]]
binding = "KV_USERS"
id = "4b8b4bc3a7e04729933c33ab2df01016"

[[kv_namespaces]]
binding = "KV_PROFILES"
id = "8ddd91937e024774969a1ab816ce3926"

[[kv_namespaces]]
binding = "KV_LOCATIONS"
id = "8ff2ffe50f47478994415b66945a9f8f"

[[kv_namespaces]]
binding = "KV_POI"
id = "9371be3728c04e5e92142daa97ca843d"

[vars]
# Environment variables if needed
